### ISSUE TITLE
help needed getting a birt reprot to run

### ISSUE THREAD

**Issue by sferket** [vaab/report_birt#2]
We successfully installed the module. 
We added a new report as described in the README. this is the report:
Name: test
Object: sale.order
Action Usage: <empty>
Service Name: sale.order
Report Type: birt
Report file: <empty>

birt tab:
Birt viewer URL: http://127.0.0.1:8080/birt-viewer
Report file: myreport.rptdesign
Output format: pdf

Report Parameter:
Name: test 
Value: 123

Security:
Sales / User

When we go to sale -> orders -> select any order
We would expect to see this report under Reports (where we also see Quotations / Order), but nothing is shown here.

What are we doing wrong?

**Comment by vaab** [comment]
This is classical behavior (even if it sucks ;) ). Historically, modules that adds reports do not link object with the report you created. So `report_birt` won't do it also. 

There's a way to do it through several menus and actions that I've lost track how to do so, because I found it very inconvenient and so I created module which does this for you: https://github.com/vaab/report_add_action

This module adds a button at the bottom of the report form which allows you to create or remove the action to print the corresponding report directrly from target object views (in your case 'sale.order' form view). This is what you are missing I believe.

I hope this answers your issue correctly.

**Comment by sferket** [comment]
We finally found some time to continue this investigation. 

After successfully installing the module on v7, including the very useful module report_add_action.
We now have the report available in sale.order.
After clicking the report we get this error message:
global name 'XmlParser' is not defined

"(<type 'exceptions.NameError'>, NameError("global name 'XmlParser' is not defined",), <traceback object at 0x5a46a28>)"

Any idea how we can fix this one?

**Comment by vaab** [comment]
You should set the report type to "birt" this should get you going on. But this is a bug. I'm on it.

**Comment by vaab** [comment]
This has been corrected in ba96fc7d32f36daef05e142d158a8ccaad35421d . If you have any other issues, could you please create new issues: github allows me to easily link commits with issues and I would rather cleanly separate different issues. 

Nonetheless, your last issue resolution has been committed. Thank you again for the report.

Can you please confirm that this is working for you ?

**Comment by sferket** [comment]
No, still the same error. Iĺl open a new bug for it.

**Comment by vaab** [comment]
All issues seems to have been cleared out. If you don't feel alike, please re-open the issue. Thanks for your reports !
